on:
  workflow_dispatch:
  schedule:
  - cron: '5 9 * * 5,6'
jobs:
  Phigros:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: true 
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.x'
    - run: |
        git config --global user.name 'GithubAction'
        git config --global user.email 'seed@gmail.com'
    - run: sh main.sh ${user_name}:${{ secrets.GITHUB_TOKEN }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 注入Token
